apiVersion: v1
kind: Service
metadata:
  name: moveinsync-service
spec:
  selector:
    app: moveinsync
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8501  # Container port